service/controllers/account.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from ..auth import Auth
from flask_cas import login_required
from ..forms.accounts import Edit_Profile_Form
from .. import db

blueprint = Blueprint('account', __name__, url_prefix='/account')

@blueprint.before_request
def rquire_login():
    if not ('user' in session or request.path.startswith(url_for('.login'))):
        return render_template('errors/403.html')
    pass

@blueprint.route('/login')
@login_required
def login():
    Auth.attempt();
    return redirect(url_for('content.index'))

@blueprint.route('/logout')
def logout():
    Auth._logout()
    return redirect(url_for('cas.logout', _external=True))

@blueprint.route('/edit', methods=['GET', 'POST'])
def edit_profile():
    form = Edit_Profile_Form()

    if form.validate_on_submit():
        session['user'].name = form.name.data
        session['user'].email = form.email.data

        db.session.merge(session['user'])
        db.session.commit()

        flash('Profile Has Been Updated')
        return redirect(url_for('content.index'))

    else:
        if form.errors.items():
            for field, errors in form.errors.items():
                for error in errors:
                    flash(getattr(form, field).label.text + ' - ' + error)

    form.populate_form()
    return render_template('account/edit_profile.html', form=form)

service/controllers/content.py
from flask import Blueprint, render_template, redirect, session, url_for
from flask_cas import login_required
from ..auth import Auth

blueprint = Blueprint('content', __name__)

@blueprint.route('/')
def index():
    return render_template('content/index.html')

@blueprint.route('/info')
def info():
    return render_template('errors/under_construction.html')

service/controllers/dddprint.py
from flask import Blueprint, render_template, session, redirect, url_for, flash
from ..forms.prints import Print_Submission
from ..models.prints import Print

blueprint = Blueprint('3dprint', __name__, url_prefix='/account/3dprint')

@blueprint.before_request
def required_login():
    if not 'user' in session:
        return redirect(url_for('account.login'))
    pass

@blueprint.route('/request', methods=['GET', 'POST'])
def request():
    form = Print_Submission()

    if form.validate_on_submit():
        flash("Validated", "alert")
    else:
        flash("Failed", "alert")

    if len(form.prints) == 0:
        form.prints = [Print()]

    return render_template('3dprint/request.html', form=form)

@blueprint.route('/view')
def view():
    return render_template('errors/under_construction.html')
    pass

service/controllers/manage.py
from flask import Blueprint, render_template, session, redirect, url_for

blueprint = Blueprint('manage', __name__, url_prefix='/manage')

@blueprint.before_request
def required_priv():
    if 'user' not in session:
        return redirect(url_for('account.login'))
    if not session['user'].role >= 1:
        return redirect(url_for('content.index'))
    pass

@blueprint.route('/')
def index():
    return redirect(url_for('content.index'))
    pass

@blueprint.route('/prints')
def prints():
    if not session['user'].role >= 1:
        return render_template('errors/403.html')

    return render_template('manage/prints.html')
    pass

@blueprint.route('/access')
def access():
    return render_template('manage/access.html')
    pass

service/frontend/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% if title %}{{ title }}{% else %}Innovation Lab{% endif %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="author" type="text/plain" href="/humans.txt">
        <link rel="stylesheet" href="/dist/css/bootstrap.css">
        <link rel="stylesheet" href="/dist/css/font-awesome.css">
        <link rel="stylesheet" href="/dist/css/style.css">
        {% block styles %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">

                <!-- Navbar Header Content -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand">Innovation Lab</div>
                </div>

                <div id="navbar" class="navbar-collapse collapse">

                    <!-- Left Side Navbar -->
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url_for('content.index') }}">Home</a></li>
                        <li><a href="{{ url_for('content.info') }}">Info</a></li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">3D Printing<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('3dprint.request') }}">Submit Request</a></li>
                                <li><a href="{{ url_for('3dprint.view') }}">View Submissions</a></li>
                            </ul>
                        </li>
                    </ul>

                    <!-- Right Side Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        {% if is_logged_in() %}
                            {% if is_maintainer() %}
                                <li>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Control Panel
                                        <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        {% if is_admin() %}
                                            <li role="separator" class="divider"></li>
                                            <li><a href="{{ url_for('manage.access') }}">Manage User Access</a></li>
                                        {% endif %}
                                        <li role="separator" class="divider"></li>
                                        <li><a href="{{ url_for('manage.prints') }}">Manage Prints</a></li>
                                    </ul>
                                </li>
                            {% endif %}
                        {% endif %}
                        <li>
                            {% if not is_logged_in() %}
                                <a href="{{ url_for('account.login') }}">Login</a>
                            {% else %}
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                   aria-haspopup="true" aria-expanded="false">{{ get_sid() }}<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ url_for('account.edit_profile') }}">Edit Profile</a></li>
                                    <li role="seperator" class="divider"></li>
                                    <li><a href="{{ url_for('account.logout')}}">Logout</a></li>
                                </ul>
                            {% endif %}
                        </li>
                    </ul>
                </div> <!--/#navbar-->
            </div> <!--/.container-fluid-->
        </nav>

        {% block content %}{% endblock %}
        
        <footer>
            <p class="text-center">Copyright &copy; 2016-{{ year }} Ruben Castaneda</p>
        </footer>
        <script src="/dist/js/jquery.js"></script>
        <script src="/dist/js/bootstrap.js"></script>
        {% block scripts %}{% endblock %}
    </body>
</html>

service/frontend/templates/macros.html
{% macro form_field(form, field, print_status=True) -%}
    {% set has_label = kwargs.pop('has_label', True) %}
    {% set placeholder = '' %}
    {% if not has_label %}
        {% set placeholder = field.label.text %}
    {% endif %}
    {% set field_status = '' %}
    {% if form.errors and (form.submitted or (form.is_submitted() and form.submit.data)) %}
        {# form.submit.data for support multiple forms on page #}
        {# form.submitted - manual control for form without button (ajax) #}
        {# If form has error, password field would be empty in repeat form
           and user need to retype this value.
           That is why we need to mark password field always as `error`,
           to draw user attention
         #}
        {# Simulate error for password field (because if form has errors this fields is empty after reloading page) #}
        {# Can reset this simulations with field.hide_error = True (need to sing in form) #}
        {% if field.type == 'PasswordField' and not field.hide_error %}
            {% set field_status = 'error' %}
            {% set field_errors = ['Please retype password'] %}
        {% else %}
            {% if field.errors %}
                {% set field_status = 'error' %}
            {% else %}
                {% set field_status = 'success' %}
            {% endif %}
        {% endif %}
    {% endif %}
    <div class="form-group {{ field_status }}">
         {% if has_label and field.label.text and 'BooleanField' not in field.type %}
            <label for="{{ field.id }}" class="control-label">
                {{ field.label.text }}{% if field.flags.required %} <span class="required">*</span>{% endif %}
            </label>
        {% endif %}
        <div class="controls">
            {% set class_ = kwargs.pop('class_', '') %}
            {% if 'BooleanField' in field.type %}
                <div class="checkbox">
                    <label for="{{ field.id }}">
                        {{ field(class_=class_, **kwargs) }}
                        {{ field.label.text | safe }}
                    </label>
                </div>
            {% elif 'RadioField' in field.type %}
                {% for value, label, checked in field.iter_choices() %}
                    <div class="radio">
                    {% if checked  %}
                        <label>
                            <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}"
                              checked="True">{{ label }}
                        </label>
                    {% else %}
                        <label>
                            <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}">{{ label }}
                        </label>
                    {% endif %}
                    </div>
                {% endfor %}
            {% else %}
                {% set class_ = class_ ~ ' form-control' %}
                {% set prepend = kwargs.pop('prepend', None) %}
                {% set append = kwargs.pop('append', None) %}
                {% if append or prepend %}
                    {% if append and prepend %}
                        <div class="input-group input-group-prepend input-group-append">
                            <span class="input-group-addon">{{ prepend | safe  }}</span>
                            {{ field(class_=class_, placeholder=placeholder, **kwargs) }}
                            <span class="input-group-addon">{{ append | safe }}</span>
                        </div>
                    {% elif prepend %}
                        <div class="input-group input-group-prepend">
                            <span class="input-group-addon">{{ prepend | safe  }}</span>
                            {{ field(class_=class_, placeholder=placeholder, **kwargs) }}
                        </div>
                    {% elif append %}
                        <div class="input-group input-group-append">
                            {{ field(class_=class_, placeholder=placeholder, **kwargs) }}
                            <span class="input-group-addon">{{ append | safe  }}</span>
                        </div>
                    {% endif %}
                {% else %}
                    {{ field(class_=class_, placeholder=placeholder, **kwargs) }}
                {% endif %}
            {% endif %}
            {% if field.description %}
                <p class="help-block">{{ field.description|safe }}</p>
            {% endif %}
            {% if print_status %}
                {% if field_status == 'error' %}
                    <p class="error">{{ field.errors|join('<br/>') or field_errors|join('<br/>') }}</p>
                {% elif  field_status == 'success' %}
                    <p class="success">Field is ok</p>
                {% endif %}
            {% endif %}
        </div>
    </div>
{%- endmacro %}

service/frontend/templates/page.html
{% extends 'layout.html' %}

{% block content %}
{% block pagecontent %}
{%- if content %}
    {{ content }}
{%- endif %}
{% endblock %}
{% endblock %}